

services:
  postgres:
    image: postgres:15
    container_name: university-postgres
    environment:
      POSTGRES_USER: akbota
      POSTGRES_PASSWORD: 4912
      POSTGRES_DB: university_test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U akbota -d university_test"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: .
    container_name: university-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PORT: 8080
      DATABASE_URL: "postgresql://akbota:4912@postgres:5432/university_test?sslmode=disable"
      JWT_SECRET: "AkbotaUniversityAppSecret123!"
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres_data: