# render.yaml
services:
  - type: web
    name: university-app
    env: docker
    dockerfilePath: ./hw_5_jwt/Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: university-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 8080
    healthCheckPath: /health
    autoDeploy: true

databases:
  - name: university-db
    databaseName: university
    user: akbota
    plan: free